### ISSUE TITLE
big problem

### ISSUE THREAD

**Issue by Vendicated** [DiamondMiner88/advent-of-code-2022#1]
HOP OFF KOTLIIIIIIIINNNN

**Comment by MeguminSama** [comment]
yop

**Comment by rushiiMachine** [comment]
![oie_A8moezjPe4l7](https://user-images.githubusercontent.com/33725716/205122958-f5f2e718-0654-42be-94ec-896d0edc3114.png)

**Comment by MeguminSama** [comment]
HOW

**Comment by mantikafasi** [comment]
AGREED SWITCH TO JAVA

**Comment by Vap0r1ze** [comment]
BEN

**Comment by MeguminSama** [comment]
> AGREED SWITCH TO JAVA

DO NOT

**Comment by rushiiMachine** [comment]
DO NOT

**Comment by Vap0r1ze** [comment]
AGREED SWITCH TO SCALA

**Comment by MeguminSama** [comment]
DISAGREED SWITCH TO :trollface:

**Comment by Vap0r1ze** [comment]
THERE IS TROLL FACE IN GITHUB??

**Comment by MeguminSama** [comment]
:trollface:

**Comment by 144reasons** [comment]
:trollface:

**Comment by Vap0r1ze** [comment]
:trollface:
